# build: docker build -t generalmeow/mongodb:<TAG>-arm
# run: docker run -d -p 27017:27017 --name mongodb -v <>:/data/db generalmeow/mongodb:<TAG>-arm
FROM hypriot/rpi-alpine-scratch
RUN apk update && \
apk upgrade && \
apk add bash
#rm -rf /var/cache/apk
MAINTAINER Paul Hoang 2017-01-16
RUN ["mkdir", "-p", "/data/db"]
RUN ["mkdir", "-p", "/home/files"]
RUN ["mkdir", "-p", "/home/mongodb"]
VOLUME /data/db
