# build: docker build -t generalmeow/mongodb:<TAG>-arm
# run: docker run -d -p 27017:27017 --name mongodb -v <>:/data/db generalmeow/mongodb:<TAG>-arm
FROM resin/rpi-raspbian
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "mongodb"]
EXPOSE 27017
EXPOSE 28017
MAINTAINER Paul Hoang 2017-01-16
RUN ["mkdir", "-p", "/data/db"]
VOLUME /data/db
ENTRYPOINT ["mongod"]
